'use client'

import { FormEvent, useEffect, useRef, useState } from 'react'
import { motion, useInView, useScroll, useSpring, useTransform } from 'framer-motion'
import { ArrowUpRight, Check, Clock3, Mail, MapPin, Menu, MessageCircle, Phone, Shield, X } from 'lucide-react'

const WHATSAPP_URL = 'https://wa.me/919999155702?text=Hello%20Court%20Challan%2C%20I%20need%20assistance.'
const heroImage = '/court-hero.png'
const challanImage = '/court-challan-service.png'
const blacklistImage = '/blacklist-service.png'
const ease = [0.22, 1, 0.36, 1] as const
const reveal = { hidden: { opacity: 0, y: 36 }, visible: { opacity: 1, y: 0 } }

function Brand({ light = false }: { light?: boolean }) { return <a href="#home" className={`flex items-center gap-2.5 ${light ? 'text-white' : 'text-[#b9823f]'}`} aria-label="Court Challan home"><span className="grid size-8 place-items-center rounded-sm border border-current"><Shield className="size-4" strokeWidth={1.5} /></span><span className="text-[10px] font-semibold uppercase leading-[1.05] tracking-[.18em]">Court<br />Challan</span></a> }
function WhatsAppButton({ dark = false, compact = false }: { dark?: boolean; compact?: boolean }) { return <motion.a whileHover={{ scale: 1.025, filter: 'brightness(1.08)' }} whileTap={{ scale: .97 }} href={WHATSAPP_URL} target="_blank" rel="noreferrer" className={`inline-flex items-center justify-between gap-4 rounded-full px-5 py-2.5 text-sm ${dark ? 'bg-[#151515] text-white' : 'bg-white text-[#25211e]'} ${compact ? 'min-w-[174px]' : 'min-w-[198px]'}`}><span className="flex items-center gap-2"><MessageCircle className="size-3.5" /> Chat on Whatsapp</span><span className={`grid size-7 place-items-center rounded-full ${dark ? 'bg-white text-black' : 'bg-black text-white'}`}><ArrowUpRight className="size-4" /></span></motion.a> }

function Navbar() {
  const [open, setOpen] = useState(false)
  const [scrolled, setScrolled] = useState(false)
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 28); window.addEventListener('scroll', onScroll, { passive: true }); onScroll(); return () => window.removeEventListener('scroll', onScroll) }, [])
  const links = [['Home', '#home'], ['Reviews', '#reviews'], ['Services', '#services'], ['Contact', '#contact']]
  return <motion.nav initial={{ y: -18, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ duration: .7, ease }} className={`fixed inset-x-0 top-0 z-20 px-6 py-5 text-white transition-[background-color,box-shadow,backdrop-filter] duration-500 md:px-12 lg:px-16 ${scrolled ? 'bg-black/35 shadow-lg backdrop-blur-md' : 'bg-transparent'}`}><div className="mx-auto flex max-w-[1160px] items-center justify-between"><div className="flex items-center gap-7"><Brand light /><span className="hidden h-7 w-px bg-white/60 md:block" /><div className="hidden items-center gap-9 text-sm md:flex">{links.map(([label, href], i) => <motion.a key={label} href={href} initial={{ opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .15 + i * .07, duration: .5, ease }} whileHover={{ y: -1, color: '#e9c28b' }}>{label}</motion.a>)}</div></div><div className="hidden md:block"><WhatsAppButton compact /></div><button className="md:hidden" onClick={() => setOpen(!open)} aria-label={open ? 'Close menu' : 'Open menu'}>{open ? <X /> : <Menu />}</button></div>{open && <motion.div initial={{ opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }} className="mt-5 flex flex-col gap-4 rounded-2xl bg-black/70 p-5 text-sm backdrop-blur md:hidden">{links.filter(([label]) => label !== 'Reviews').map(([label, href]) => <a key={label} href={href} onClick={() => setOpen(false)}>{label}</a>)}<WhatsAppButton compact /></motion.div>}</motion.nav>
}

function Hero() {
  const { scrollY } = useScroll()
  const y = useTransform(scrollY, [0, 700], [0, 70])
  return <section id="home" className="relative flex min-h-[760px] items-end overflow-hidden bg-[#3b271c] text-white sm:min-h-[820px]"><motion.img initial={{ opacity: 0, scale: 1.05 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 1.2, ease }} style={{ y }} src={heroImage} alt="Courthouse with vehicle, challan notice, and gavel" className="absolute inset-0 size-full object-cover object-center" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(35,20,12,.82),rgba(51,31,19,.48)_52%,rgba(30,20,15,.52))]" /><Navbar /><div className="relative z-10 mx-auto w-full max-w-[1160px] px-6 pb-20 pt-40 md:px-12 lg:px-16 lg:pb-24"><motion.div initial="hidden" animate="visible" transition={{ staggerChildren: .1, delayChildren: .35 }} className="max-w-[650px]"><motion.div variants={reveal} transition={{ duration: .65, ease }} className="mb-8 flex items-center gap-3 text-sm font-medium"><span className="h-px w-12 bg-white/80" /> PROFESSIONAL LEGAL ASSISTANCE</motion.div><h1 className="max-w-[700px] text-[clamp(3.5rem,8vw,6.7rem)] font-light leading-[.94] tracking-[-.065em]">{['Resolve Vehicle', 'Court Challans', 'Without the Hassle'].map((line) => <motion.span key={line} variants={reveal} transition={{ duration: .75, ease }} className="block">{line}</motion.span>)}</h1><motion.p variants={reveal} transition={{ duration: .65, ease }} className="mt-8 max-w-[560px] text-base leading-6 text-white/90 md:text-lg">We provide professional assistance for pending court challans, blacklist-related vehicle issues, and legal procedural support.</motion.p><motion.div variants={reveal} transition={{ duration: .65, ease }} className="mt-9"><WhatsAppButton /></motion.div><motion.div variants={reveal} transition={{ duration: .65, ease }} className="mt-16 flex items-center gap-5 border-l border-white/70 pl-5"><div className="text-2xl tracking-[.18em]">★★★★★</div><div className="text-base font-medium">100+ Positive Client Reviews</div></motion.div></motion.div></div></section>
}

function SectionReveal({ children, className = '' }: { children: React.ReactNode; className?: string }) { return <motion.div initial="hidden" whileInView="visible" viewport={{ once: true, amount: .18 }} variants={reveal} transition={{ duration: .75, ease }} className={className}>{children}</motion.div> }
function Services() { return <section id="services" className="scroll-mt-20 bg-white px-6 py-20 text-black md:px-12 md:py-28"><div className="mx-auto max-w-[900px]"><SectionReveal><h2 className="text-center text-4xl font-semibold tracking-[-.04em] md:text-5xl">Our Services</h2></SectionReveal><div className="mt-20 flex flex-col gap-24 md:mt-24 md:gap-32"><ServiceItem title="Court Challan Assistance" description="Assistance for pending court challans including documentation, procedural guidance, and coordination support to help you resolve the issue efficiently." image={challanImage} alt="Court documents, gavel, and vehicle" /><ServiceItem reverse title="Vehicle Blacklist Clearance Support" description="Support for blacklist-related vehicle issues including verification, documentation, and legal procedural assistance." image={blacklistImage} alt="Blacklist clearance documents and vehicle" /></div></div></section> }
function ServiceItem({ title, description, image, alt, reverse = false }: { title: string; description: string; image: string; alt: string; reverse?: boolean }) { return <article className="flex flex-col gap-8"><SectionReveal><h3 className="text-center text-3xl font-normal tracking-[-.035em] md:text-4xl">{title}</h3></SectionReveal><div className={`flex flex-col items-center gap-10 md:flex-row md:gap-16 ${reverse ? 'md:flex-row-reverse' : ''}`}><motion.div initial={{ opacity: 0, x: reverse ? 34 : -34, scale: .96 }} whileInView={{ opacity: 1, x: 0, scale: 1 }} viewport={{ once: true, amount: .2 }} transition={{ duration: .8, ease }} className="w-full max-w-[390px] overflow-hidden rounded-xl"><motion.img whileHover={{ scale: 1.03 }} transition={{ duration: .5, ease }} src={image} alt={alt} className="aspect-[1.7] w-full object-cover" /></motion.div><motion.p initial={{ opacity: 0, x: reverse ? -28 : 28 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true, amount: .2 }} transition={{ duration: .75, delay: .12, ease }} className="max-w-[480px] text-xl leading-[1.28] tracking-[-.025em] md:text-[26px]">{description}</motion.p></div></article> }

function Statistics() { return <section id="reviews" className="scroll-mt-20 bg-white px-6 pb-28 pt-4 md:px-12"><div className="mx-auto flex max-w-[900px] flex-col justify-between gap-12 text-center sm:flex-row sm:gap-5"><Stat value={7} suffix="+" label="Years of experience" delay={0} /><Stat value={200} suffix="+" label="Happy Clients" delay={.1} /><Stat value={500} suffix="+" label="Challan Cleared" delay={.2} /></div></section> }
function Stat({ value, suffix, label, delay }: { value: number; suffix: string; label: string; delay: number }) { const ref = useRef(null); const inView = useInView(ref, { once: true, amount: .6 }); const [count, setCount] = useState(0); useEffect(() => { if (!inView) return; const start = performance.now(); const timer = requestAnimationFrame(function tick(now) { const progress = Math.min((now - start) / 700, 1); setCount(Math.round(value * (1 - Math.pow(1 - progress, 3)))); if (progress < 1) requestAnimationFrame(tick) }); return () => cancelAnimationFrame(timer) }, [inView, value]); return <motion.div ref={ref} initial={{ opacity: 0, y: 25 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: .65, delay, ease }} className="flex-1"><div className="text-4xl font-medium tracking-[-.04em] md:text-5xl">{count}{suffix}</div><div className="mt-2 text-sm">{label}</div></motion.div> }

function ContactForm() { const [submitted, setSubmitted] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; if (!form.checkValidity()) { setError('Please complete all required fields.'); form.reportValidity(); return }; setError(''); setLoading(true); window.setTimeout(() => { setLoading(false); setSubmitted(true); form.reset() }, 650) }; if (submitted) return <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="flex min-h-[390px] flex-col items-center justify-center text-center"><div className="mb-5 grid size-14 place-items-center rounded-full bg-white text-[#8f5c32]"><Check /></div><h3 className="text-2xl font-medium">Thank you for reaching out.</h3><p className="mt-3 max-w-[310px] text-sm text-white/75">Our team will review your details and contact you shortly.</p><button onClick={() => setSubmitted(false)} className="mt-6 text-sm underline underline-offset-4">Send another enquiry</button></motion.div>; return <form onSubmit={submit} className="mt-7 grid grid-cols-1 gap-4 sm:grid-cols-2" noValidate><Field label="Name" placeholder="Your Name" /><Field label="Vehicle Number" placeholder="eg: KL 07 A 1234" /><Field label="Phone" placeholder="1234567890" type="tel" /><label className="flex flex-col gap-2 text-xs font-medium">Issue Regarding<select required defaultValue="" className="h-10 rounded-lg border-0 bg-[#382d27]/80 px-3 text-sm font-normal text-white outline-none transition focus:bg-[#30251f] focus:ring-2 focus:ring-white/30"><option value="" disabled>Select an issue</option><option>Court Challan</option><option>Blacklist Clearance</option><option>Other Vehicle Issue</option></select></label><label className="col-span-full flex flex-col gap-2 text-xs font-medium">Message<textarea required placeholder="I need..." className="min-h-20 resize-y rounded-lg border-0 bg-[#382d27]/80 px-3 py-3 text-sm font-normal text-white outline-none transition focus:bg-[#30251f] focus:ring-2 focus:ring-white/30 placeholder:text-white/35" /></label>{error && <p className="col-span-full text-xs text-[#ffd7bf]">{error}</p>}<motion.button whileHover={{ scale: 1.01 }} whileTap={{ scale: .98 }} disabled={loading} className="col-span-full flex h-11 items-center justify-between rounded-full bg-white px-5 text-sm font-medium text-[#241c18] transition hover:bg-[#f2e9df] disabled:cursor-wait disabled:opacity-70">{loading ? 'Sending...' : 'Submit form'} <span className="grid size-7 place-items-center rounded-full bg-black text-white"><ArrowUpRight className="size-4" /></span></motion.button></form> }
function Field({ label, placeholder, type = 'text' }: { label: string; placeholder: string; type?: string }) { return <label className="flex flex-col gap-2 text-xs font-medium">{label}<input required type={type} placeholder={placeholder} className="h-10 rounded-lg border-0 bg-[#382d27]/80 px-3 text-sm font-normal text-white outline-none transition focus:bg-[#30251f] focus:ring-2 focus:ring-white/30 placeholder:text-white/35" /></label> }
function ContactSection() { return <section id="contact" className="relative scroll-mt-20 overflow-hidden bg-[linear-gradient(135deg,#9b6537,#c58a52_45%,#e1b184)] px-6 py-16 text-white md:px-12 md:py-20"><motion.div initial={{ opacity: 0, scale: 1.04 }} whileInView={{ opacity: 1, scale: 1 }} viewport={{ once: true, amount: .15 }} transition={{ duration: 1, ease }} className="pointer-events-none absolute inset-0"><motion.div style={{ y: useTransform(useScroll().scrollY, [0, 1800], [0, -30]) }} className="absolute -bottom-48 left-[35%] size-[800px] rounded-full border border-white/20" /><div className="absolute -bottom-64 left-[49%] size-[850px] rounded-full border border-white/15" /></motion.div><div className="relative mx-auto grid max-w-[900px] items-center gap-7 md:grid-cols-[1fr_1.05fr]"><motion.div initial={{ opacity: 0, x: -32 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true, amount: .2 }} transition={{ duration: .75, ease }} className="rounded-2xl border border-white/10 bg-[#5d412c]/60 p-6 shadow-2xl backdrop-blur-sm md:p-7"><h2 className="text-center text-2xl font-medium leading-tight md:text-[26px]">Get Assistance for Your Vehicle Issue</h2><p className="mx-auto mt-4 max-w-[340px] text-center text-sm leading-5 text-white/85">Fill out the form and our team will contact you regarding your vehicle court challan or blacklist-related issue.</p><ContactForm /></motion.div><motion.div initial={{ opacity: 0, x: 32 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true, amount: .2 }} transition={{ duration: .75, delay: .1, ease }}><ContactInfo /></motion.div></div></section> }
function ContactInfo() { return <div className="rounded-2xl border border-white/10 bg-[#5d412c]/60 p-7 shadow-2xl backdrop-blur-sm md:p-8"><h2 className="text-2xl font-medium md:text-[27px]">Need Immediate Assistance?</h2><p className="mt-6 max-w-[340px] text-center text-sm leading-5 text-white/90 md:text-left">Contact our team directly on WhatsApp for faster support regarding vehicle court challans and blacklist-related issues.</p><div className="mt-6 flex justify-center md:justify-start"><WhatsAppButton dark compact /></div><div className="mt-7 flex flex-col gap-5 text-sm"><span className="flex items-center gap-3"><Phone className="size-4" /> +91 04843582847</span><span className="flex items-center gap-3"><Clock3 className="size-4" /> 9995155702</span><span className="flex items-center gap-3"><Mail className="size-4" /> uniquewehelp@gmail.com</span><span className="flex items-center gap-3"><MapPin className="size-4" /> Unique Online Solutions, Kaloor</span></div></div> }
function Footer() { return <motion.footer initial="hidden" whileInView="visible" viewport={{ once: true, amount: .2 }} variants={reveal} transition={{ duration: .75, ease }} className="bg-[#171717] px-6 py-12 text-white/55 md:px-12 md:py-14"><div className="mx-auto flex max-w-[900px] flex-col justify-between gap-12 md:flex-row"><div className="max-w-[270px]"><Brand light /><p className="mt-7 text-xs leading-[1.55]">Professional assistance for vehicle court challans and blacklist-related legal procedures across Kerala. Fast, reliable, and hassle-free support for resolving vehicle legal issues.</p><p className="mt-6 text-xs">© 2026 Court Challan. All rights reserved.</p></div><div className="grid grid-cols-2 gap-16 text-xs"><div><h3 className="mb-4 text-sm font-medium text-white">Sections</h3><div className="flex flex-col gap-4">{[['Home', '#home'], ['Services', '#services'], ['Contact', '#contact'], ['Whatsapp', WHATSAPP_URL]].map(([label, href]) => <motion.a key={label} whileHover={{ x: 3, color: '#fff' }} href={href}>{label}</motion.a>)}</div></div><div><h3 className="mb-4 text-sm font-medium text-white">Socials</h3><div className="flex flex-col gap-4">{['Twitter', 'Instagram', 'TikTok'].map((item) => <motion.a key={item} whileHover={{ x: 3, color: '#fff' }} href="#">{item}</motion.a>)}</div></div></div></div></motion.footer> }

function ScrollProgress() { const { scrollYProgress } = useScroll(); const scaleX = useSpring(scrollYProgress, { stiffness: 100, damping: 30, restDelta: .001 }); return <motion.div style={{ scaleX, transformOrigin: '0%' }} className="fixed inset-x-0 top-0 z-50 h-[3px] bg-[#c28a4d]" aria-hidden="true" /> }
export default function Page() { return <main className="overflow-hidden bg-white"><ScrollProgress /><Hero /><Services /><Statistics /><ContactSection /><Footer /></main> }
